config/routes.rb
Beerme::Application.routes.draw do

controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :styles
  resources :check_ins
  resources :users

resources :beers do
       collection do
         get 'search'
       end
end

  root :to => 'beers#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :user_name, :user_type, :password , :password_confirmation
  validates :user_name, :user_type, :password, :password_confirmation, :presence => true
  
  has_secure_password
  has_many :check_in
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :save_path
	
	
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <% if current_user && current_user.user_type == 2%>
  <div class="field">
    <%= f.label :user_type %><br />
    <%= f.select :user_type, [["Choose one"],["User", 1],["Admin", 2]]  %> 
  </div>
  <%else %>
  <div class="field">
    <%= f.hidden_field :user_type, :value => 1  %> 
  </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Password" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="beer">
<h1>Edit user info</h1>
<% if current_user %>
<%= render 'form' %>

<br />

<%= link_to 'View', @user %> | <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %><br /><br />
<div class="button">
<%= link_to 'Back', users_path %>
</div>
<% end %>
</div>

app/views/users/index.html.erb
<div class="home">
  
<h1>Drinkers</h1>






<% @users.each do |user| %>
<div class="beer">
 
    <h2><%= link_to user.user_name, user %></h2>
    <p>User type: <strong><%= user.user_type %></strong></p>
    <p>Email: <strong><%= user.email %></strong></p>
    
  <% if current_user && current_user.user_name == user.user_name || current_user && current_user.user_type == 2 %>
    <small><%= link_to 'edit', edit_user_path(user) %> | 
    <%= link_to 'delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></small>
  <% end %>

  
  </div>
<% end %>


<br />


<div class="button">
<% if current_user && current_user.user_type == 2 %>
<%= link_to 'New User', new_user_path %>
<% end %>
</div>
</div>

app/views/users/new.html.erb
<div class="beerintro">
	<h1>What's BeerMe</h1>
	<p class="intro">BeerMe is the new social beer drinking application that allows you to share with your friends the beer that you are drinking.<p>
	<p class="intro">Browse our ever growing selection of beers that other people have shared.  
	</p>
	<p class="intro">Sign up today and start sharing.</p>
	<p class="intro">Cheers!!!
	</p>

</div>

<div class="beer">
	<h1>Sign up!</h1>
	
	<%= render 'form' %>
	
	<div class="redbutton">
	<%= link_to 'Cancel', beers_path %>
	</div>
</div>

<div class="beerintro">
	<h1>Sign up Today</h1>
	<p class="intro">By registering you get many benefits that include:
	</p>
	<ul>
		<li>Allows you to check in any beer</li>
		<li>Create reviews for the beer that you check in</li>
		<li>Automatically qualify for our weekly beer drawings</li>
		<li>Many more...</li>
	</ul>

</div>

app/views/users/show.html.erb
<div class="single home">


<div class="button">
<%= link_to 'Back', users_path %>
</div>
<p id="notice"><%= notice %></p>


<h1> <%= @user.user_name %></h1>

<div class="beer">
<p>
  <b>User type:</b>
  <%= @user.user_type %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<% if current_user && current_user.user_type == 2  %>
<small>
<%= link_to 'edit', edit_user_path(@user) %> | <%= link_to 'delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
</small>
<% end %>
<% else if current_user && current_user.user_name == @user.user_name  %>
<small>
<%= link_to 'edit', edit_user_path(@user) %>
</small>
<% end %>


</div>
</div>

<h2>Reviews by <%= @user.user_name %></h2>
  <% @user.check_in.order("created_at DESC").each do |r|  %>
  <div class="beer">
<p>
<h2> <%= link_to r.beer.title, r.beer %></h2><br>
Rating: <%= r.rating %><br>
Review: <%= r.review %><br>
<%= r.wishlist ? "On wishlist" : "Not on wishlist" %><br>


Review date: <%= r.created_at %>

</p>
<% if current_user  %>
<div><%= link_to 'edit', edit_check_in_path(r) %></div>
<% end %>
</div>
<% end %>

</div>