config/routes.rb
Beerme::Application.routes.draw do

controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :styles
  resources :check_ins
  resources :users

resources :beers do
       collection do
         get 'search'
       end
end

  root :to => 'beers#index'

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
  attr_accessible :beer_id, :rating, :review, :user_id, :wishlist
  
  belongs_to :beer
  belongs_to :user
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  # GET /check_ins
  # GET /check_ins.json
  def index
    @check_ins = CheckIn.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @check_ins }
    end
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
    @check_in = CheckIn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @check_in }
    end
  end

  # GET /check_ins/new
  # GET /check_ins/new.json
  def new
    @check_in = CheckIn.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @check_in }
    end
  end

  # GET /check_ins/1/edit
  def edit
    @options = Beer.all.collect {|m| [m.title, m.id] }
    @check_in = CheckIn.find(params[:id])
  end

  # POST /check_ins
  def create
    @check_in = CheckIn.new(params[:check_in])
     if current_user
      @check_in.user_id = current_user.id
     end
     if @check_in.save
      redirect_to @check_in.beer, notice: 'Check-in was successfully created.'
     else
      render action: "new"
    end

    #respond_to do |format|
    #  if @check_in.save
    #    redirect_to @check_in, notice: 'Check in was successfully created.' 
    #  else
    #    render action: "new" 
    #  end
    #end
  end

  # PUT /check_ins/1
  def update
    @check_in = CheckIn.find(params[:id])
    
    
      if current_user and current_user == @check_in.user
      respond_to do |format|
        if @check_in.update_attributes(params[:check_in])
          format.html { redirect_to @check_in.beer, notice: 'Check in was successfully updated.' }
        else
          format.html {  render action: "edit" }
        end
      end
    else
      redirect_to session[:previous], :notice => "Illegal action"
    end
   
  end

  # DELETE /check_ins/1
  def destroy
    @check_in = CheckIn.find(params[:id])
    @check_in.destroy

    respond_to do |format|
       format.html { redirect_to session[:previous] }
    end
  end
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/views/check_ins/_form.html.erb
<%= form_for(@check_in) do |f| %>
  <% if @check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% @check_in.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :review %><br />
    <%= f.text_area :review, :rows => "3" %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.select :rating, [1, 2, 3, 4, 5] %>
  </div>
  <div class="field">
    <%= f.label :wishlist %><br />
    <%= f.check_box :wishlist %>
  </div>
  <!--<div class="field">
    <%= f.label :beer_id %><br />
    <%= f.text_field :beer_id  %>
  </div>
   <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div> -->
  <div class="actions">
    <%= submit_tag "Check In"  %>
  </div>
<% end %>

app/views/check_ins/edit.html.erb
<h1>Editing <%= @check_in.beer.title%> Review</h1>

<%= render 'form' %>

<div class="redbutton"><%= link_to 'delete', check_in_path, method: :delete, data: { confirm: 'Are you sure?' } %></div><br /><br />
<!-- <%= link_to 'Show', @check_in %> | -->
<div class="button"><%= link_to 'Back', check_ins_path %></div>

app/views/check_ins/index.html.erb
<div class="beertable">
<h1>Beer Check-ins</h1>

<table>
  <tr>
    <th>Review</th>
    <th>Rating</th>
    <th>Wishlist</th>
    <th>Beer</th>
    <th>Drinker</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @check_ins.each do |check_in| %>
  <tr>
    <td><%= check_in.review %></td>
    <td><%= check_in.rating %></td>
    <td><%= check_in.wishlist %></td>
    <td><%= check_in.beer_id %></td>
    <td><%= check_in.user_id %></td>
    <td><%= link_to 'Show', check_in %></td>
    <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
    <td><%= link_to 'Destroy', check_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<div class="button">
<%= link_to 'New Check in', new_check_in_path %>
</div>

app/views/check_ins/new.html.erb
<h1>New check-in</h1>

<%= render 'form' %>

<div class="button">
<%= link_to 'Back', check_ins_path %>
</div>

app/views/check_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Review:</strong>
  <%= @check_in.review %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @check_in.rating %>
</p>

<p>
  <strong>Wishlist:</strong>
  <%= @check_in.wishlist %>
</p>

<p>
  <strong>Beer:</strong>
  <%= @check_in.beer_id %>
</p>

<p>
  <strong>Drinker:</strong>
  <%= @check_in.user_id %>
</p>

<div class="button">
<%= link_to 'Edit', edit_check_in_path(@check_in) %> &nbsp;  <%= link_to 'delete', check_in_path, method: :delete, data: { confirm: 'Are you sure?' } %><br /><br />
<%= link_to 'Back', check_ins_path %>
</div>