config/routes.rb
Beerme::Application.routes.draw do

controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :styles
  resources :check_ins
  resources :users

resources :beers do
       collection do
         get 'search'
       end
end

  root :to => 'beers#index'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  attr_accessible :brewery, :note, :title, :style
  
  has_many :check_in
  
  validates :title, :presence => true
  validates :brewery, :presence => true
  
  #validates :rating, :numericality => true, :length => {:within => 1..5} 
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  
  before_filter :check_login, :except => [:index, :search, :show]
  before_filter :save_path
  
  
  # GET /beers
  def index
    @beers = Beer.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /beers/1
  def show
    @beer = Beer.find(params[:id])
    @check_in = CheckIn.new

    respond_to do |format|
      format.html # show.html.erb
    end
  end
  
  # SEARCH
  def search
       if params[:search_text]
         match_term = "%" + params[:search_text] + "%"
         @beers = Beer.where("title LIKE ?", match_term) + Beer.where("brewery LIKE?", match_term)
       end
  end
  
  
  # GET /beers/new
  def new
    @beer = Beer.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /beers/1/edit
  def edit
    @beer = Beer.find(params[:id])
  end

  # POST /beers
  def create
    @beer = Beer.new(params[:beer])

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully added.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /beers/1
  def update
    @beer = Beer.find(params[:id])

    respond_to do |format|
      if @beer.update_attributes(params[:beer])
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        
      else
        format.html { render action: "edit" }
        
      end
    end
  end

  # DELETE /beers/1
  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url }
    end
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :brewery %><br />
    <%= f.text_field :brewery %>
  </div>
    <div class="field">
    <%= f.label :note, "Description" %><br />
    <%= f.text_area :note %>
  </div>
    <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style  %>
  </div>

  <!-- Removed from the Beers - added to Reviews
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.select :rating, [['Rate this beer'], ['Piss Water', 1], ['Not Good', 2],
['Decent', 3], ['Really Good', 4],
                               ['Superb', 5]]     %>
  </div> -->
  <!-- Removed from the Beers - added to Reviews
  <div class="field">
    <%= f.check_box :wishlist %><%= f.label :wishlist, 'Add to Wishlist' %> 
    
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Edit beer</h1>

<%= render 'form' %>

<div class="button">
<%= link_to 'Show', @beer %> &nbsp;
<%= link_to 'Back', beers_path %>
</div>

app/views/beers/index.html.erb
<div class="home">
<h1>All Beers</h1>



<% if @beers %>

         <% @beers.each do |beer| %>
         
         <div class="beer">
         <h2> <%= link_to beer.title, beer %></h2>

            
            <p class="brewery">Brewery: <strong><%= beer.brewery %></strong></p>
            
            <p class="style">Style: <strong><%= beer.style %></span></strong></p>
            
            <p class="checkin">Number of check-ins: <strong><%= CheckIn.count(:all, :conditions => ['beer_id = ?', beer.id]) %></strong> </p>
	
			
            
         </div> 
         <% end %>




<% end %>

<br />
<div class="button">
<% if current_user %>
<%= link_to 'New Beer', new_beer_path %>
<% end %>
</div>
</div>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<div class="button">
<%= link_to 'Back', beers_path %>
</div>

app/views/beers/search.html.erb
<h1> Searched for "<%= params[:search_text] %>"  <small> &nbsp;<a href="<%= beers_url %>">clear search</a></small></h1>


<% if @beers %>

         <% @beers.each do |beer| %>
         
         <div class="beer">
         <h2> <%= link_to beer.title, beer %></h2>
            <p class="brewery">Brewery: <strong><%= beer.brewery %></strong></p>
            
            <p class="style">Style: <strong><%= beer.style %></span></strong></p>
            
            <p class="checkin">Number of check-ins: <strong><%= CheckIn.count(:all, :conditions => ['beer_id = ?', beer.id]) %></strong> </p>
						</div> 
         <% end %>




<% end %>

app/views/beers/show.html.erb
<div class="single home">


<div class="button" style="margin:0px">
<%= link_to 'Back', beers_path %>
</div>
<p id="notice"><%= notice %></p>

<div class="beer">
<h2>
  <%= @beer.title %>
</h2>

<p class="brewery"><strong>
  <%= @beer.brewery %>
</p> <p class="style">
  <%= @beer.style %>
</p></strong>

<p class="note">
  <%= @beer.note %>
</p>


             <% if current_user  %>
             <small>
				<%= link_to 'Edit', edit_beer_path(@beer) %> 
				<% if current_user.user_type == 2  %> |
					<%= link_to 'Delete', @beer, method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
             </small>
             <% end %>

</div>
<div class="beercheckin">
<% if current_user %> 

  <h3>Check In</h3>
  
      <%= form_for(@check_in) do |f| %>
  <% if @check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% @check_in.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.hidden_field :beer_id, :value => @beer.id %>

  <div class="field">
    <%= f.label :review %><br />
    <%= f.text_area :review, :rows => "3" %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.select :rating, [1, 2, 3, 4, 5] %>
  </div>
  <div class="field">
    <%= f.label :wishlist %><br />
    <%= f.check_box :wishlist %>
  </div>


  <div class="actions">
    <%= submit_tag "Check In" %> &nbsp; <%= link_to 'Cancel', beers_path %>
  </div>
<% end %>

</div>
  <% end %>

 <div class="checkins"> 
 <h3>Check-ins</h3> 
  <% @beer.check_in.order("created_at DESC").each do |r|  %>
  
  <div class="beer">
<h2><%= link_to r.user.user_name, r.user  %></h2>
<p>

Rating: <strong><%= r.rating %></strong><br>
Review: <strong><%= r.review %></strong><br>
<%= r.wishlist ? "On wishlist" : "Not on wishlist" %><br>


Review date: <strong><%= r.created_at %></strong>

</p>

<% if current_user && current_user.user_name == r.user.user_name || current_user && current_user.user_type == 2 %>      
      <small>
	  <%= link_to 'edit', edit_check_in_path(r) %> | <%= link_to 'delete', r, method: :delete, data: { confirm: 'Are you sure?' } %>
	  </small>
  <% else %>

<% end %>

</div>
<% end %>
</div>