config/routes.rb
Beerme::Application.routes.draw do

controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :styles
  resources :check_ins
  resources :users

resources :beers do
       collection do
         get 'search'
       end
end

  root :to => 'beers#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerMe - The Beer List</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
	<h3 class="logo"><a href="/beers/">BeerMe</a></h3>
	
	  <%= form_tag search_beers_path, :method => 'get' do %>
	  <div class="search">
		<p>
		<strong><%= label_tag :search_text, "Search" %></strong>
		<%= text_field_tag :search_text, params[:search_text] %>
		
		<span class="actions">
		<%= submit_tag 'Search' %>
		</span></p>
		<% end%>
	</div>
	
	<div id="nav">
		<ul>
			<li><%= link_to "Home", beers_url %></li>
			<% if current_user %>
			<li><a href="/users">Drinkers</a></li>
			<% end %>
			<% if !current_user %>
			<li><%= link_to 'Register', new_user_path %></li>
			<% end %>
			<!--li><a href="/">Beers</a></li-->
			<!--li><a href="/check_ins">Check Ins</a></li-->
			<!--li><a href="/styles">Styles</a></li -->
		</ul>
	</div>
	
	
</div>
<div class="content">
  
  <% if current_user %>
  <p class="username">
<%= current_user.user_name %> is logged in 
(<%= link_to 'Logout', logout_url, :method => :delete %>)</p>
<% else %>
<%= form_tag login_url do %>
  <p>
  <label for="name">Name:</label>
  <%= text_field_tag :user_name, params[:user_name] %>

  <label for="password">Password:</label>
  <%= password_field_tag :password %>


  
  <%= submit_tag 'Login', :class => :loginButton %>
    </p>
  <% end %>
<% end %>
  
  
<%= yield %>
</div>

</body>
</html>